// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package common

import (
	"github.com/dysodeng/app/internal/dal/dao/common"
	common2 "github.com/dysodeng/app/internal/service/domain/common"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitValidCodeAppService() ValidCodeAppService {
	smsDao := common.NewSmsDao()
	smsDomainService := common2.NewSmsDomainService(smsDao)
	mailDao := common.NewMailDao()
	mailDomainService := common2.NewMailDomainService(mailDao)
	validCodeDomainService := common2.NewValidCodeDomainService(smsDomainService, mailDomainService)
	commonValidCodeAppService := NewValidCodeAppService(validCodeDomainService)
	return commonValidCodeAppService
}

// wire.go:

var ValidCodeAppServiceSet = wire.NewSet(NewValidCodeAppService, common2.ValidCodeDomainServiceSet)
