// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package common

import (
	"github.com/dysodeng/app/internal/dal/dao/common"
	common2 "github.com/dysodeng/app/internal/service/domain/common"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitAreaAppService() AreaAppService {
	areaDao := common.NewAreaDao()
	areaDomainService := common2.NewAreaDomainService(areaDao)
	commonAreaAppService := NewAreaAppService(areaDomainService)
	return commonAreaAppService
}

func InitValidCodeAppService() ValidCodeAppService {
	smsDao := common.NewSmsDao()
	smsDomainService := common2.NewSmsDomainService(smsDao)
	mailDao := common.NewMailDao()
	mailDomainService := common2.NewMailDomainService(mailDao)
	validCodeDomainService := common2.NewValidCodeDomainService(smsDomainService, mailDomainService)
	commonValidCodeAppService := NewValidCodeAppService(validCodeDomainService)
	return commonValidCodeAppService
}

// wire.go:

var AreaAppServiceSet = wire.NewSet(NewAreaAppService, common2.AreaDomainServiceSet)

var ValidCodeAppServiceSet = wire.NewSet(NewValidCodeAppService, common2.ValidCodeDomainServiceSet)
