database:
  default: main
  migration:
    enabled: true
  main:
    driver: mysql
    host: 127.0.0.1
    port: 3306
    database: test
    username: root
    password: root
    max_idle_conns: 50
    max_open_conns: 200
    max_conn_lifetime: 300
