redis:
  main:
    # 模式选择: standalone, cluster, sentinel
    mode: standalone
    # 单机模式配置
    host: 127.0.0.1
    port: 6379
    password:
    db: 0
    key_prefix:
    # 集群模式配置
    cluster:
      addrs:
        - "127.0.0.1:7000"
        - "127.0.0.1:7001"
        - "127.0.0.1:7002"
      password:
    # 哨兵模式配置
    sentinel:
      master_name: "mymaster"
      sentinel_addrs:
        - "127.0.0.1:26379"
        - "127.0.0.1:26380"
        - "127.0.0.1:26381"
      password:
      sentinel_password:
      db: 0
    # 连接池配置
    pool:
      min_idle_conns: 10
      max_retries: 3
      pool_size: 100
      
  cache:
    mode: standalone
    host: 127.0.0.1
    port: 6379
    password:
    db: 1
    key_prefix:
    cluster:
      addrs: []
      password:
    sentinel:
      master_name:
      sentinel_addrs: []
      password:
      sentinel_password:
      db: 1
    pool:
      min_idle_conns: 10
      max_retries: 3
      pool_size: 100
      
  mq:
    mode: standalone
    host: 127.0.0.1
    port: 6379
    password:
    db: 2
    key_prefix:
    cluster:
      addrs: []
      password:
    sentinel:
      master_name:
      sentinel_addrs: []
      password:
      sentinel_password:
      db: 2
    pool:
      min_idle_conns: 10
      max_retries: 3
      pool_size: 100
