// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/dysodeng/app/internal/dal/dao/user"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitUserDomainService() DomainService {
	dao := user.NewUserDao()
	userDomainService := NewUserDomainService(dao)
	return userDomainService
}

// wire.go:

var DomainServiceSet = wire.NewSet(user.NewUserDao, NewUserDomainService)
